name: montagem_web
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  page_transition: ^2.0.4
  firebase_core: ^1.1.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  intl: ^0.17.0
  http:
  url_launcher:
  brasil_fields:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
      - family: Secular One
        fonts:
          - asset: assets/fonts/SecularOne-Regular.ttf
      - family: Nunito
        fonts:
          - asset: assets/fonts/Nunito-Regular.ttf


